### ISSUE TITLE
Improved meta identification API for AKN3

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/cobalt#27]
Particularly for structured documents:

* [x] get/set FRBRalias
* [ ] get/set FRBRsubtype
* [ ] getters and settings for other work, expression and manifestation identification elements
